# SITE CONFIGURATION
baseurl: ""
url: "https://u-schmidt.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Udo's Website                                                  # site's title
description: "A website about personal projects, work and life"       # used by search engines
avatar: assets/img/me-04.png                                          # Empty for no avatar in navbar
favicon: assets/img/trunky02.png                                      # Icon displayed in the tab

# Header and footer text
header_text: Udo's blog about personal projects, work and life  # Change Blog header text
header_feature_image: assets/img/header/stgeorg-01.jpg
header_feature_image_responsive: false
footer_text: >
  Random staff about personal projects, work and life. <br>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for comments, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: default                                        # Enable mermaid-js for diagrams, use theme: base, forest, dark, default, neutral
google_analytics:                                       # Measurement ID, e.g. "G-00000"
cookie_consent: true                                    # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
  quiet_deps: true
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude:
  - ".idea"
  - ".jekyll-cache"
  - ".jekyll-metadata"
  - ".sass-cache"
  - "Gemfile"
  - "Gemfile.lock"
  - "type-on-strap.gemspec"
  - "vendor"
  - "node_modules"
  - "assets/node_modules"
  - "assets/Dockerfile"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "LICENSE"
  - ".github"
  - "test-results"

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
